/**
 * Mock tennis data for development.
 * In production, this will be replaced by Cloudflare D1 queries.
 */

export const atpRankings = [
  { rank: 1, name: 'Jannik Sinner', country: 'ITA', points: 11830, change: 0 },
  { rank: 2, name: 'Carlos Alcaraz', country: 'ESP', points: 9255, change: 0 },
  { rank: 3, name: 'Alexander Zverev', country: 'GER', points: 7860, change: 1 },
  { rank: 4, name: 'Novak Djokovic', country: 'SRB', points: 6540, change: -1 },
  { rank: 5, name: 'Daniil Medvedev', country: 'RUS', points: 5830, change: 0 },
  { rank: 6, name: 'Taylor Fritz', country: 'USA', points: 4920, change: 2 },
  { rank: 7, name: 'Casper Ruud', country: 'NOR', points: 4510, change: -1 },
  { rank: 8, name: 'Andrey Rublev', country: 'RUS', points: 4200, change: -1 },
  { rank: 9, name: 'Holger Rune', country: 'DEN', points: 3870, change: 1 },
  { rank: 10, name: 'Grigor Dimitrov', country: 'BUL', points: 3620, change: -1 },
  { rank: 11, name: 'Alex de Minaur', country: 'AUS', points: 3490, change: 0 },
  { rank: 12, name: 'Hubert Hurkacz', country: 'POL', points: 3280, change: 2 },
  { rank: 13, name: 'Tommy Paul', country: 'USA', points: 3110, change: -1 },
  { rank: 14, name: 'Ben Shelton', country: 'USA', points: 2970, change: 3 },
  { rank: 15, name: 'Stefanos Tsitsipas', country: 'GRE', points: 2830, change: -2 },
];

export const wtaRankings = [
  { rank: 1, name: 'Aryna Sabalenka', country: 'BLR', points: 10590, change: 0 },
  { rank: 2, name: 'Iga Swiatek', country: 'POL', points: 8525, change: 0 },
  { rank: 3, name: 'Coco Gauff', country: 'USA', points: 7250, change: 1 },
  { rank: 4, name: 'Jessica Pegula', country: 'USA', points: 5815, change: -1 },
  { rank: 5, name: 'Jasmine Paolini', country: 'ITA', points: 5390, change: 0 },
  { rank: 6, name: 'Elena Rybakina', country: 'KAZ', points: 4950, change: 1 },
  { rank: 7, name: 'Zheng Qinwen', country: 'CHN', points: 4720, change: -1 },
  { rank: 8, name: 'Emma Navarro', country: 'USA', points: 4180, change: 2 },
  { rank: 9, name: 'Daria Kasatkina', country: 'RUS', points: 3860, change: 0 },
  { rank: 10, name: 'Barbora Krejcikova', country: 'CZE', points: 3540, change: -2 },
];

export const atpRaceRankings = [
  { rank: 1, name: 'Jannik Sinner', country: 'ITA', points: 5300, change: 0 },
  { rank: 2, name: 'Carlos Alcaraz', country: 'ESP', points: 4900, change: 1 },
  { rank: 3, name: 'Alexander Zverev', country: 'GER', points: 4200, change: -1 },
  { rank: 4, name: 'Daniil Medvedev', country: 'RUS', points: 3500, change: 0 },
  { rank: 5, name: 'Casper Ruud', country: 'NOR', points: 3100, change: 2 },
  { rank: 6, name: 'Stefanos Tsitsipas', country: 'GRE', points: 2800, change: 1 },
  { rank: 7, name: 'Alex de Minaur', country: 'AUS', points: 2600, change: -2 },
  { rank: 8, name: 'Taylor Fritz', country: 'USA', points: 2400, change: 0 },
  { rank: 9, name: 'Andrey Rublev', country: 'RUS', points: 2200, change: 1 },
  { rank: 10, name: 'Grigor Dimitrov', country: 'BUL', points: 2100, change: -1 },
];

export const wtaRaceRankings = [
  { rank: 1, name: 'Iga Swiatek', country: 'POL', points: 6100, change: 0 },
  { rank: 2, name: 'Aryna Sabalenka', country: 'BLR', points: 5800, change: 0 },
  { rank: 3, name: 'Elena Rybakina', country: 'KAZ', points: 4300, change: 1 },
  { rank: 4, name: 'Coco Gauff', country: 'USA', points: 3900, change: -1 },
  { rank: 5, name: 'Jasmine Paolini', country: 'ITA', points: 3500, change: 2 },
  { rank: 6, name: 'Zheng Qinwen', country: 'CHN', points: 3200, change: 1 },
  { rank: 7, name: 'Danielle Collins', country: 'USA', points: 3000, change: -2 },
  { rank: 8, name: 'Jessica Pegula', country: 'USA', points: 2800, change: 0 },
  { rank: 9, name: 'Emma Navarro', country: 'USA', points: 2500, change: 1 },
  { rank: 10, name: 'Marta Kostyuk', country: 'UKR', points: 2200, change: -1 },
];

export const tournaments = [
  {
    id: 'wimbledon-2026',
    name: 'Wimbledon',
    city: 'London',
    country: 'GBR',
    surface: 'Grass',
    category: 'Grand Slam',
    startDate: '2026-06-29',
    endDate: '2026-07-12',
    tour: 'atp',
    status: 'upcoming',
  },
  {
    id: 'roland-garros-2026',
    name: 'Roland Garros',
    city: 'Paris',
    country: 'FRA',
    surface: 'Clay',
    category: 'Grand Slam',
    startDate: '2026-05-25',
    endDate: '2026-06-08',
    tour: 'atp',
    status: 'completed',
  },
  {
    id: 'halle-open-2026',
    name: 'Halle Open',
    city: 'Halle',
    country: 'GER',
    surface: 'Grass',
    category: 'ATP 500',
    startDate: '2026-06-15',
    endDate: '2026-06-21',
    tour: 'atp',
    status: 'live',
  },
  {
    id: 'queens-club-2026',
    name: "Queen's Club Championships",
    city: 'London',
    country: 'GBR',
    surface: 'Grass',
    category: 'ATP 500',
    startDate: '2026-06-15',
    endDate: '2026-06-21',
    tour: 'atp',
    status: 'live',
  },
  {
    id: 'eastbourne-2026',
    name: 'Eastbourne International',
    city: 'Eastbourne',
    country: 'GBR',
    surface: 'Grass',
    category: 'WTA 500',
    startDate: '2026-06-22',
    endDate: '2026-06-28',
    tour: 'wta',
    status: 'upcoming',
  },
  {
    id: 'bad-homburg-2026',
    name: 'Bad Homburg Open',
    city: 'Bad Homburg',
    country: 'GER',
    surface: 'Grass',
    category: 'WTA 250',
    startDate: '2026-06-22',
    endDate: '2026-06-28',
    tour: 'wta',
    status: 'upcoming',
  },
  {
    id: 'us-open-2026',
    name: 'US Open',
    city: 'New York',
    country: 'USA',
    surface: 'Hard',
    category: 'Grand Slam',
    startDate: '2026-08-31',
    endDate: '2026-09-13',
    tour: 'atp',
    status: 'upcoming',
  },
  {
    id: 'canadian-open-2026',
    name: 'Canadian Open',
    city: 'Toronto',
    country: 'CAN',
    surface: 'Hard',
    category: 'Masters 1000',
    startDate: '2026-08-08',
    endDate: '2026-08-16',
    tour: 'atp',
    status: 'upcoming',
  },
];

export const recentMatches = [
  {
    id: 'm1',
    tournamentId: 'halle-open-2026',
    tournamentName: 'Halle Open',
    round: 'QF',
    player1: 'J. Sinner',
    player2: 'H. Rune',
    score: '6-4, 7-5',
    winner: 'J. Sinner',
    date: '2026-06-18',
  },
  {
    id: 'm2',
    tournamentId: 'halle-open-2026',
    tournamentName: 'Halle Open',
    round: 'QF',
    player1: 'A. Zverev',
    player2: 'T. Paul',
    score: '6-3, 3-6, 7-6(4)',
    winner: 'A. Zverev',
    date: '2026-06-18',
  },
  {
    id: 'm3',
    tournamentId: 'queens-club-2026',
    tournamentName: "Queen's Club",
    round: 'SF',
    player1: 'C. Alcaraz',
    player2: 'T. Fritz',
    score: '7-6(2), 6-4',
    winner: 'C. Alcaraz',
    date: '2026-06-19',
  },
  {
    id: 'm4',
    tournamentId: 'roland-garros-2026',
    tournamentName: 'Roland Garros',
    round: 'F',
    player1: 'C. Alcaraz',
    player2: 'J. Sinner',
    score: '6-3, 2-6, 7-5, 6-1',
    winner: 'C. Alcaraz',
    date: '2026-06-08',
  },
];

export const lastUpdated = '2026-06-10T02:00:00Z';
